# ベースイメージとして最新のUbuntuを使用
FROM ubuntu:latest

# 必要なパッケージの更新とインストール
RUN apt-get update && apt-get install -y \
    g++ \
    make \
    vim \
    && apt-get clean

# 作業ディレクトリを設定
WORKDIR /workspace

# ホストのカレントディレクトリをコンテナの /workspace にマウント
VOLUME ["/workspace"]

